apiVersion: apps/v1
kind: Deployment
metadata:
  name: web # Название нашего объекта Deployment
spec:
  replicas: 3 # Начнем с одного пода
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector: # Укажем, какие поды относятся к нашему Deployment:
    matchLabels: # - это поды с меткой
      app: web # app и ее значением web
  template: # Теперь зададим шаблон конфигурации пода
    metadata:
      labels: # Метки в формате key: value
        app: web
    spec: # Описание Pod
      initContainers:
        - name: init
          image: busybox:1.31.0
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
          volumeMounts:
            - name: app
              mountPath: /app
      containers: # Описание контейнеров внутри Pod
      - name: web # Название контейнера
        image: anmcqueen/mcqueen_repo:hw # Образ из которого создается контейнер
        readinessProbe:       # Добавим проверку готовности
          httpGet:            # веб-сервера отдавать
            path: /index.html # контент
            port: 8000
        livenessProbe:
          tcpSocket: { port: 8000 }
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        emptyDir: {}